export const GET_JOB_TITLE_DATA_SUCCESS = 'GET_JOB_TITLE_DATA_SUCCESS';
export const GET_JOB_TITLE_DATA_FAILURE = 'GET_JOB_TITLE_DATA_FAILURE';
export const CREATE_JOB_TITLE_DATA_SUCCESS = 'CREATE_JOB_TITLE_DATA_SUCCESS';
export const CREATE_JOB_TITLE_DATA_FAILURE = 'CREATE_JOB_TITLE_DATA_FAILURE';
export const UPDATE_JOB_TITLE_DATA_SUCCESS = 'UPDATE_JOB_TITLE_DATA_SUCCESS';
export const UPDATE_JOB_TITLE_DATA_FAILURE = 'UPDATE_JOB_TITLE_DATA_FAILURE';
export const DELETE_JOB_TITLE_DATA_SUCCESS = 'DELETE_JOB_TITLE_DATA_SUCCESS';
export const DELETE_JOB_TITLE_DATA_FAILURE = 'DELETE_JOB_TITLE_DATA_FAILURE';
